### ISSUE TITLE
ZamConvo ompile error

### ISSUE THREAD

**Issue by tvraman** [zamaudio/zam-plugins#100]
variable typo? kParameterIsAutomable

**Comment by zamaudio** [comment]
@tvraman that plugin never really existed.  Please see master branch.

**Comment by tvraman** [comment]
But I'm on master and still get the same error; has the git repo moved?
origin	https://github.com/zamaudio/zam-plugins.git (fetch)
origin	https://github.com/zamaudio/zam-plugins.git (push)

git branch
* master
08:49:43 zam-plugins $ make
make -C dpf/dgl
make[1]: Entering directory '/home/raman/sourceforge/zam-plugins/dpf/dgl'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/raman/sourceforge/zam-plugins/dpf/dgl'
make -C plugins/ZamComp
make[1]: Entering directory '/home/raman/sourceforge/zam-plugins/plugins/ZamComp'
Compiling ZamCompPlugin.cpp
ZamCompPlugin.cpp: In member function ‘virtual void DISTRHO::ZamCompPlugin::initParameter(uint32_t, DISTRHO::Parameter&)’:
ZamCompPlugin.cpp:39:32: error: ‘kParameterIsAutomatable’ was not declared in this scope; did you mean ‘kParameterIsAutomable’?
   39 |         parameter.hints      = kParameterIsAutomatable;
      |                                ^~~~~~~~~~~~~~~~~~~~~~~
      |                                kParameterIsAutomable
make[1]: *** [../../dpf/Makefile.plugins.mk:134: ../../build/ZamComp/ZamCompPlugin.cpp.o] Error 1
make[1]: Leaving directory '/home/raman/sourceforge/zam-plugins/plugins/ZamComp'
make: *** [Makefile:29: ZamComp] Error 2
08:49:48 zam-plugins $ 
--

**Comment by tvraman** [comment]
problem went away after starting with a fresh git clone
