### ISSUE TITLE
HeadX2: 48000 vs 44100 warning

### ISSUE THREAD

**Issue by tvraman** [zamaudio/zam-plugins#101]
get a convolv2 warning re rate mismatch, but changing  the #define in convolution.cpp to 44100 doesn't make the error go away

**Comment by zamaudio** [comment]
@tvraman the warning is harmless, it just alerts you that it will need to do extra work to resample the presets to match your active sample rate.

**Comment by zamaudio** [comment]
You cannot use LV2 plugins with asound.conf as far as I know.  Sorry, I had to drop ladspa for ZamHeadX2.
