### ISSUE TITLE
Build breaks: ld: error: version script assignment of 'global' to symbol 'VSTPluginMain' failed: symbol not defined

### ISSUE THREAD

**Issue by yurivict** [zamaudio/zam-plugins#102]
See the [log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p3f853a69d83c_s74fe298c82/logs/zam-plugins-lv2-4.2.log).

Version: 4.2
FreeBSD 15 CURRENT

**Comment by zamaudio** [comment]
This should be fixed next time I update DPF

**Comment by yurivict** [comment]
Do you know when is this expected to happen?

**Comment by zamaudio** [comment]
I'm waiting for AU support to be stable in DPF, then I will bump the version of this submodule and include AU support.

**Comment by zamaudio** [comment]
@yurivict can you confirm this error is gone?

**Comment by yurivict** [comment]
@zamaudio It looks like this error has disappeared since 4.3

**Comment by zamaudio** [comment]
Thanks, closing as fixed
