### ISSUE TITLE
[Feature request] StudioRack integration

### ISSUE THREAD

**Issue by RustoMCSpit** [zamaudio/zam-plugins#103]
It's an open-source plugin manager called StudioRack:
https://github.com/studiorack

The aim of the project is to provide a free open-source way to manage plugin dependencies and their versions. It would involve the following steps:

    Publish a Github release containing the plugin source along with metadata plugins.json
    Tag your Github repository with studiorack-plugin so it can be discovered
    Wait for the studiorack-registry to index your plugin (every 24 hours)
    Check the registry feed for your plugin to appear

**Comment by zamaudio** [comment]
@RustoMCSpit Why do I need to add a tag? Doesn't that mean every version I make needs to have the tag updated?  That will also end up in a new github release which is undesirable.

**Comment by RustoMCSpit** [comment]
> @RustoMCSpit Why do I need to add a tag? Doesn't that mean every version I make needs to have the tag updated? That will also end up in a new github release of my software which is undesirable.

you can make issue requests in https://github.com/studiorack and the dev will get back to you. im not familiar with the inner workings sorry!

**Comment by zamaudio** [comment]
@RustoMCSpit I don't have time for this.   Happy to accept a Pull Request with the `plugins.json` file if you want to create it.

**Comment by RustoMCSpit** [comment]
alright thats

> @RustoMCSpit I don't have time for this. Happy to accept a Pull Request with the `plugins.json` file if you want to create it.

alright understandable, the dev is currently talkign about a new method in https://discord.gg/9D94f98PxP so i'll see what needs to be done

**Comment by zamaudio** [comment]
Closing for now

**Comment by RustoMCSpit** [comment]
> Closing for now

did you do it?
