### ISSUE TITLE
LADSPA plugins not recognised by non-mixer

### ISSUE THREAD

**Issue by jrigg** [zamaudio/zam-plugins#26]
The LADSPA versions of zam-plugins aren't recognised by non-mixer. At first I thought this might be the Plugin Unique IDs  being too large - the official IDs as allocated by Richard Furse, who maintains the list of reserved LADSPA IDs, are still below 10000. Looking into it further I see that the IDs are unsigned long int, so I guess that isn't the problem.

**Comment by jrigg** [comment]
Think I found the reason: non-mixer doesn't load plugins marked as not RT capable. The TAP plugins (also not RT capable) load OK but IIRC there's a workaround in the code to accommodate them.

**Comment by zamaudio** [comment]
Thanks for reporting this, please pull for fix.  I don't think I can make ZamTube HARD_RT_CAPABLE though.  Please let me know if it works.

**Comment by jrigg** [comment]
Fixed :-)

All (apart from Zam Tube) work fine now.
