### ISSUE TITLE
zamsfz does not produce any sound

### ISSUE THREAD

**Issue by Fak3** [zamaudio/zam-plugins#27]
I installed current version of zam-plugins from git (f75581f76d3e0acd8b604c07ff1e69a649b505ff - that is v3.5+)
Zamsfz plugin loaded just fine in carla, but it produces no sound, no matter what sfz file i open.
For example i tried this: SalamanderGrandPianoV3_48khz24bit from http://freepats.zenvoid.org/Piano/
Mentioned above sfz file plays just fine in linuxsampler.

**Comment by Fak3** [comment]
Log from console: http://susepaste.org/28574323

**Comment by zamaudio** [comment]
This is experimental plugin so far, sorry.
