### ISSUE TITLE
ZamTube tonestack ladspa and lv2 generic controls

### ISSUE THREAD

**Issue by magnetophon** [zamaudio/zam-plugins#28]
When changing the tonestack in ladspa, or with the lv2 generic controls, in both A3 and 4, I get silence at certain values. (7 and higher).
Then at 17 it works again.
Once the val has been 7, nr 1-6 also stop working. Once I pass 0 again, 1-6 work again.

The lv2 generic gui shows a probable cause: rounding errors in the values.  (for example 8.999999).

**Comment by zamaudio** [comment]
This bug has been fixed.

**Comment by magnetophon** [comment]
@zamaudio great, thanks!

I cannot test right now, but I'll keep you updated.
