### ISSUE TITLE
In ZaMultiCompX2UI.cpp Missing DSP callback switch

### ISSUE THREAD

**Issue by Stazed** [zamaudio/zam-plugins#31]
In ZaMultiCompX2UI.cpp the below function seems to be missing a switch call for the stereo/Max toggle.
This causes the plugin to fail to load preset value on/off of the toggle on reload.
I added the below case which seemed to fix the problem on my machine.

using latest git clone 7/21/15

// DSP Callbacks

//line 275

void ZaMultiCompX2UI::parameterChanged(uint32_t index, float value)
{
    switch (index)
    {
     case ZaMultiCompX2Plugin::paramStereoDet:
        fToggleStereo->setValue(value);
        break;
    }
    
Thanks for all the great plugins!!

**Comment by zamaudio** [comment]
Thanks for pointing that out!  Fixed in 922601d76b
