### ISSUE TITLE
ZaMultiComp missing two threshold controls

### ISSUE THREAD

**Issue by jrigg** [zamaudio/zam-plugins#32]
ZaMultiComp(X2) seems to be missing two threshold controls. This makes it impossible to set up in what I'd regard as a sensible configuration for a multiband compressor. Most full range musical signals have higher levels at lower frequencies, so this in effect makes it a low frequency compressor. Strictly speaking it should also have separate attack and release controls per band as HF often needs faster settings than LF. If I need a multi-band comp on the mix bus I have to use a crossover plus several ZamCompX2 (an excellent compressor BTW) which defeats the object of having a multi-band one :-(

**Comment by zamaudio** [comment]
Glad to have some feedback on this.  Yes you are correct, ZaMultiComp was just a test run for my first multiband attempt, i didnt want to include too many confusing controls so i simplified them and dropped a lot of flexibility in the process.  Then I wrote the stereo version and added some new features.  I guess if i was doing it properly I should rewrite both of them to include all of the above, but look how many knobs there will be!

**Comment by jrigg** [comment]
Yes there would be quite a lot of knobs :-). The Calf multiband compressor GUI handles this with separate tabs for each band. The LinuxDSP MBC has fewer controls than the Calf one and has quite a compact GUI without resorting to tabs. One thing both of those GUIs include is a readout of the exact values of settings - working blind is OK if you have time for trial and error, but if you know the settings you need and are in a hurry it really slows things down if you can't see them. I use the ZamComp with the generic jalv.gtk GUI because of this. Being able to type in settings in a text field (as in Calf plugins) is also very useful.

**Comment by zamaudio** [comment]
![zamulticompx2](https://cloud.githubusercontent.com/assets/3164348/10298444/1373690a-6c2b-11e5-85c8-83efcf4c900e.png)

Well I think i fixed the Stereo version (X2)... Enjoy!

**Comment by jrigg** [comment]
Works great. Thanks for fixing!

**Comment by zamaudio** [comment]
Fixed the Mono version too! Issue closed.
