### ISSUE TITLE
Add close gain to ZamGate

### ISSUE THREAD

**Issue by napcode** [zamaudio/zam-plugins#35]
In order to make the gate more useful, I'd love to see a "close gain" parameter. This gain factor defines maxium gain reduction in closed state.

**Comment by zamaudio** [comment]
I don't see the benefit myself, but this is not difficult to implement.

**Comment by napcode** [comment]
This request is essentially about the difference between gating and expanding. The gain reduction I was talking about is sometimes called expand range. 
Sometimes I simply don't want to cut the "closed signal" entirely. I just want to reduce it a few db.

**Comment by zamaudio** [comment]
Ahh I see, yes, I could add this feature.

**Comment by zamaudio** [comment]
Fixed in revision fa60d65
