### ISSUE TITLE
Add a source filter to ZamGate

### ISSUE THREAD

**Issue by napcode** [zamaudio/zam-plugins#36]
I think the gate would be more useful if it had a source filter. The filtered should then be used as analysis signal for the gate. A highpass + a lowpass fillter would be enough. 
A button to monitor the filtered signal would be nice as well.

**Comment by zamaudio** [comment]
Actually, when Ardour adds a feature to adjust pin mappings of plugin inputs, I can add a sidechain feature that will allow any other signal to be used as the detection circuit, rather than just the input signal.  I am holding off on this for the moment.

**Comment by napcode** [comment]
Sounds reasonable. Thanks for considering.
