### ISSUE TITLE
Knob position sometimes jumps when being adjusted

### ISSUE THREAD

**Issue by jamip** [zamaudio/zam-plugins#38]
When adjusting the knobs, sometimes their position jumps suddenly. I don't have a way to reproduce this consistently but it happens regularly and moving the knobs a few times is enough for the issue to show up.

**Comment by zamaudio** [comment]
I have seen this before I think.  Can you please make a note of at least one example of an actual knob that does this.  Please post the knob name and plugin it comes from.  Then I can look into it.  Thanks

**Comment by jamip** [comment]
I just opened up ZamCompx2 (LV2) and moved the ratio and release controls and they both jumped to zero. I initially tested this in Ardour but also checked it in Carla and have the same issue there. This seems to happen pretty much every time I try it. 

I am not sure if it happens with a mouse but I am using the trackpad on my laptop. I wonder if that has any connection to it? Although having said that, and if it is part of the problem, I have never seen the issue on any other plugin knobs or had any other misbehavior from the trackpad in general. Just thought I would mention it in case it does play a part.

**Comment by zamaudio** [comment]
Fixed in  3e23ce9
