### ISSUE TITLE
ZamCompX2 LADSPA analyseplugin error message

### ISSUE THREAD

**Issue by jrigg** [zamaudio/zam-plugins#40]
(EDITED)
Was: ZamCompX2 LADSPA version from current git won't load in non-mixer. analyseplugin gives the following error messages:

Now is: ZamCompX2 LADSPA version from current git produces an error message from analyseplugin:

"Stereo Detection" input, control, 0 to 1, ERROR: TOGGLED INCOMPATIBLE WITH OTHER HINT, default 0
	"Sidechain" input, control, 0 to 1, ERROR: TOGGLED INCOMPATIBLE WITH OTHER HINT, default 0

LV2 (hosted in jalv.gtk) and JACK versions work fine.

EDIT: ZamCompX2 will load in non-mixer if strip has 3 channels. See my comment below.

**Comment by falkTX** [comment]
I guess it's because I use toogled and integer at the same time.

**Comment by falkTX** [comment]
This has been fixed in https://github.com/DISTRHO/DPF/commit/8773ce84804e053b5ae80e273e0f51e3ef283d91

**Comment by jrigg** [comment]
@falkTX: Thanks for making this change.

I was actually wrong about the plugin not loading. It loads fine in non-mixer in a 3-channel strip to accommodate the extra sidechain input. I was thrown by the fact that ZamComp still loads in a single-channel strip (but sidechain input is inaccessible unless loaded in a 2-channel strip). This appears to be a quirk in non-mixer.

The error message from analyseplugin still appears but doesn't seem to affect anything. I've changed the issue title accordingly.

**Comment by zamaudio** [comment]
Updated DPF in 93cc77c should be fixed now, thanks falkTX
