### ISSUE TITLE
ZamSFZ : crash in Ardour 5.0 (Ardour 4.7 too)

### ISSUE THREAD

**Issue by trebmuh** [zamaudio/zam-plugins#45]
Here is a step-by-step how-to crash:

**Preparations:**
- I set up a SFZ (SSO "Brass - Bass Trombone Solo.sfz") with modifying all the `\` by `/` (see https://github.com/zamaudio/zam-plugins/issues/43).
- I launch Ardour 5 and open a new session.

**Ardour 5 + ZamSFZ playing fine together:**
- I create an audio+MIDI track and choose in the ZamSFZ instrument.
- I double-click on its red-line in the mixerstrip. Its GUI opens.
- I click on the "LOAD SFZ" button in its GUI and a window pops up.
- I choose the "Brass - Bass Trombone Solo.sfz".
- I connect my MIDI keyboard using the connexion matrix in the audio+MIDI track's mixerstrip. (then, I play on the MIDI keyboard and I can hear the sound as expected.)
- I rise up the gain on the ZamSFZ's plugin GUI, then I'm closing this window.
- I play on the MIDI keyboard and can still hear me.
- I set up the audio+MIDI track and the master for recording.
- I start the recording (space key) and I play. (I can still hear me playing et I can see the recording happening.)
- I stop the recording with the space key.
- I play the track. No issue, That's sounding.
- I save the session and close Ardour.

**Making it crashes:**
Now, I relaunch Ardour 5 (from the terminal to get some info) and I choose the session saved just before, and tadam ! Segfault:

```
Butler drops pool trash
Set buffering params to 262144|131072|10|10
Erreur de segmentation
```

I relaunch Ardour 5, choosing a new session, it opens. I choose to open the saved before, and tadam ! Crash with the same message.

**Information:**
Screencast: http://download.tuxfamily.org/librazik/volatile/zam-ardour5-test.mp4
Updated Debian Jessie.
Zam build from https://github.com/zamaudio/zam-plugins/commit/5d9e7c69a16c7d64da6bb30b8cac7c082edbecc8

Hope that can help,
Olivier

PS: it's been confirmed by another user using Ardour 4.7 and the same Zam-plugins build from https://github.com/zamaudio/zam-plugins/commit/5d9e7c69a16c7d64da6bb30b8cac7c082edbecc8, on a Debian Jessie too.

**Comment by trebmuh** [comment]
Some more testing with Zam build https://github.com/zamaudio/zam-plugins/commit/5d9e7c69a16c7d64da6bb30b8cac7c082edbecc8 + qtractor 0.7.8 still on the same updated Debian Jessie. Same behavior both with the LV2 and the VST versions of ZamSFZ.

Note that I spotted something which looks like another unrelated bug: https://github.com/zamaudio/zam-plugins/issues/46

Hope that helps

**Comment by funkmuscle** [comment]
I have the same issue so I tried loading a zam plugin from Carla. It froze my system for a minute the loaded the gui frame but nothing in the gui until another minute. I'm using Arch64. I think it's a gui thing because I can use the plugins with Ardour's generic gui.

**Comment by trebmuh** [comment]
@funkmuscle : did you try the ZamSFZ or another one?

**Comment by funkmuscle** [comment]
I may of posted in the wrong section both I'm having this issue with all the Zam plugins. For some reason my build never has the ZamSFZ but I love using your compressors and EQs. I just loaded ZaMultiComp in Carla, froze my system for a minute. Loaded ZamDynamicEq in Qtractor, froze my system for more than a minute. When I say froze, I mean not even the mouse moves. I thing that's why it crashes Ardour. That minute of freezing I don't think Ardour can handle.

**Comment by trebmuh** [comment]
@funkmuscle I think this is another problem then and I'd recommend you to open another issue here.

It's normal that you don't have the ZamSFZ since this is an experimental plugin. Then it's not build from the normal build action.

Last but not least, you seem to think that I'm a part of the development of the Zam* which isn't true. I'm only a user/tester. all the kudos are going to @zamaudio for developing this plugins suite.

**Comment by zamaudio** [comment]
No, damien made it not ZAMMIT


On 24 September 2016 11:35:23 AM AEST, Olivier Humbert <notifications@github.com> wrote:
>@funkmuscle I think this is another problem then and I'd recommend you
>to open another issue here.
>
>It's normal that you don't have the ZamSFZ since this is an
>experimental plugin. Then it's not build from the normal build action.
>
>Last but not least, you seem to think that I'm a part of the
>development of the Zam* which isn't true. I'm only a user/tester. all
>the kudos are going to @zamaudio for developing this plugins suite.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/zamaudio/zam-plugins/issues/45#issuecomment-249337070

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by funkmuscle** [comment]
thanx guys. Damien I'll forward this to you in another thread.

**Comment by trebmuh** [comment]
> No, damien made it not ZAMMIT

?

**Comment by zamaudio** [comment]
Error irobot reboot :p

On 25 September 2016 3:46:55 AM AEST, Olivier Humbert <notifications@github.com> wrote:
>> No, damien made it not ZAMMIT
>
>?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/zamaudio/zam-plugins/issues/45#issuecomment-249377845

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by trebmuh** [comment]
ok :)

**Comment by zamaudio** [comment]
@funkmuscle Can you please start a new issue detailing what you experienced with my plugins.  I have not seen anyone have crashes for a longggg time.  Maybe it's a simple build dependency issue.

**Comment by zamaudio** [comment]
Note that ZamSFZ is highly experimental and so I would expect crashes in this one, it's not even built by default!

**Comment by funkmuscle** [comment]
I haven't had any issues as of late either.. I thing it could of been a
dependency issue. I'll keep you posted if anything crashes happen again.
Sorry to not let you know. been quite busy.

**Comment by zamaudio** [comment]
Closing this as a stale issue, since I have updated ZamSFZ recently.  Please open a new issue if something similar happens in future.
