### ISSUE TITLE
ZamSFZ : (almost) freeze the computer in Qtractor

### ISSUE THREAD

**Issue by trebmuh** [zamaudio/zam-plugins#46]
When testing https://github.com/zamaudio/zam-plugins/issues/45 , I made the following scenario:
- open Qtractor
- create a MIDI track
- connect the MIDI track to the ZamSFZ plugin (VST version)
- load a SFZ in it
  All good till here. Now:
- connect the MIDI track to the ZamSFZ plugin (LV2 version)
- load the same SFZ in it

...bang, almost freezed.

**Edit:** note that it doesn't need to be the same SFZ bank loaded for the almost-freezed to happen

**Comment by zamaudio** [comment]
Closing this as a stale issue, since I have updated ZamSFZ recently. Please open a new issue if something similar happens in future.
