### ISSUE TITLE
ZamNoise and ZamSynth

### ISSUE THREAD

**Issue by Teteros** [zamaudio/zam-plugins#48]
I'm wondering if there is any chance for some older plugins like noise gate or synth to come back in the future?

ZamNoise does not seem to build as `ImageToggle.hpp` it uses is missing.
Same for ZamSynth.

**Comment by zamaudio** [comment]
These plugins are not part of the release for a reason, they don't sound good.  I just keep them in the tree in case someone (maybe even me) wants to improve the DSP to a point where they might be usable. Currently, they are not.

**Comment by zamaudio** [comment]
OK, ZamSynth should now work if you add it to the makefile.

**Comment by trebmuh** [comment]
I've been building ZamSynth from today's git and it works fine. No crash or strange things so far.

**Comment by trebmuh** [comment]
@zamaudio , build on a Debian Buster (stable) from https://github.com/zamaudio/zam-plugins/commit/509d498f30605af511257b1086f3b398bddbc20a, there is a strange behavior (at least, to my eyes) with ZamSynth in ardour6.

- switch the WAVEFORM/ENVELOPE button to WAVEFORM
- set the gain to +15
- toggle the WAVEFORM/ENVELOPE button to ENVELOPE
- the gain is reset to 0 (it is not expected to move)

_Please, note that the behavior is correct (ie: no reset to 0) when used as LV2 with jalv, or as standalone._

**Comment by zamaudio** [comment]
I've added ZamNoise to master branch, it's a decent noise remover now.

**Comment by trebmuh** [comment]
@zamaudio : oh nice. Are you on the way for a new release soon-ish?
