### ISSUE TITLE
gain reduction inline display for compressors

### ISSUE THREAD

**Issue by magnetophon** [zamaudio/zam-plugins#53]
It would be very handy to have a display of the gain reduction inline in Ardour.

I heard the Ardour compressor is yours as well.
For that one, I've [requested](http://tracker.ardour.org/view.php?id=7120) the same.

**Comment by zamaudio** [comment]
This is something we could look at in the future, but for now it relies on DPF to handle the ui, which I think does not support inline displays.  Closing for now.
