### ISSUE TITLE
ZamVerb LADSPA doesn't work

### ISSUE THREAD

**Issue by trebmuh** [zamaudio/zam-plugins#57]
Zam plugins build from GIT master https://github.com/zamaudio/zam-plugins/commit/7d2226adfc12f92ed4fc3d392e6a6c6dd9c0e7a0
Ardour 5.12

The standalone works fine, the LV2 as well, but the LADSPA version doesn't sound to be working when playing with the 3 controls in Ardour.

**Comment by trebmuh** [comment]
Tested with Qtractor (0.8.5), the LV2 and VST versions are fines, the LADSPA version doesn't wok any better.

**Comment by zamaudio** [comment]
This is a known issue with LADSPA not having the ability to use DPF `states`.  Please raise with DPF if this issue is blocking your workflow.

**Comment by falkTX** [comment]
I don't see how this is an issue with DPF, if a plugin uses states and can't work properly without them, then we should not enable LADSPA formats for them.
You're kinda abusing the DPF states with ZamVerb, but ignoring that I think you can just remove the LADSPA and DSSI outputs for ZamVerb and then close the issue.
Just remove the if block from https://github.com/zamaudio/zam-plugins/blob/master/plugins/ZamVerb/Makefile#L37

**Comment by zamaudio** [comment]
OK no probs.  But if DPF LADSPA ports supported states, this would not be an issue. :P

**Comment by zamaudio** [comment]
Same issue with ZamHeadX2 in 3.10

**Comment by falkTX** [comment]
LADSPA does not support states, only control or audio ports, so this is not possible in LADSPA *by design*.

**Comment by zamaudio** [comment]
Fixed in b90ee2a
