### ISSUE TITLE
Zam* LV2 : ttl definition

### ISSUE THREAD

**Issue by trebmuh** [zamaudio/zam-plugins#58]
All the LV2 plugins shows up as category : "Plugin" where it' be useful if the each one could appear as its real category.

**Comment by zamaudio** [comment]
Can you please raise this issue with DPF, since it would need to be exposed to plugins that use the framework.

**Comment by falkTX** [comment]
This is something that DPF supports, but has to be implemented by the developer.
DPF can't just automatically guess what kind of plugin type each one will be.
Please don't label things as DPF bugs without understanding the issue.

The category is set via `DISTRHO_PLUGIN_LV2_CATEGORY` macro on the DistrhoPluginInfo.h file.
It can be any string value, but better to make it a valid lv2 category.

Here's 2 examples:
https://github.com/DISTRHO/DPF-Plugins/blob/master/plugins/PingPongPan/DistrhoPluginInfo.h#L31
https://github.com/DISTRHO/DPF-Plugins/blob/master/plugins/3BandEQ/DistrhoPluginInfo.h#L30

**Comment by zamaudio** [comment]
Ah, well, my bad.  It took labelling the bug as what I thought it was to make someone point it out.  Sorry for not reading the spec.  At least I now know how to fix it.

**Comment by zamaudio** [comment]
Fixed in d3f1584
