### ISSUE TITLE
ZamTube is a CPU eater

### ISSUE THREAD

**Issue by MaxPayne86** [zamaudio/zam-plugins#61]
Hi,

I've cross-compiled this plugin for a Raspberry Pi 2 and the xruns are quite high. I cannot use this plugin
at the moment. What is the reference CPU consumption on a Intel i7 for this plugin?

As a NOTE: [here](https://github.com/MaxPayne86/rt-wdf_lv2) you can find my attempts in the past to implement a plugin using official rt-wdf library. Unfortunately I fall in the same issue: CPU consumption using this modeling approach is so high that the plugin is not usable on my platform...

**Comment by zamaudio** [comment]
Sorry, I did not design this plugin for a Raspberry Pi platform...

**Comment by laserbat** [comment]
Reducing cpu load by 300% means making it 3 times lower.

**Comment by zamaudio** [comment]
I mean, it was 25% load now its like 8%, 25/8 * 100 ~ 300 percent improvement.

**Comment by zamaudio** [comment]
I've lowered it from 8% down to 6% load now...

**Comment by zamaudio** [comment]
Sorry folks, I have had to revert the approximations, as they deviate way too far from the full solution, and sounds awful at some settings.

**Comment by zamaudio** [comment]
Closing as wont-fix

**Comment by MaxPayne86** [comment]
Hi, some time has passed, since I've seen many commits on this plugin suite, and that now zita-convolver-4.0 has been included in the sources. I have tested the last commit again this time on my board which is now Aida DSP OS (arm 64 bit). With Gain knob at 0 CPU consumption is ok, more or less 20%. But if I rise gain a little jumps to 100% with lot of xruns. With the version of jack2 I'm using it actually crashes jackd. Just as a reference, thanks.

**Comment by zamaudio** [comment]
@MaxPayne86 See above comment:
```Sorry folks, I have had to revert the approximations, as they deviate way too far from the full solution, and sounds awful at some settings.```

I did not design any of these plugins for single board ARM chips.  I am interested in high-quality sound over performance, as such I cannot make them work on low powered devices without spending tons more effort, which I just have no time to do.  Happy to take a PR if you can optimise the DSP for ARM.

**Comment by MaxPayne86** [comment]
@zamaudio yeah I've seen this comment but after this there were numerous commits so worth a try. 
At the moment I'm really busy since I'm providing both support on existing plugins and adding new features for my board. I'm interested in the topic and I've started studying existing papers on analog modeling, but without any hint this will take a long time to translate into code. For example: **getIa(...)**. It is acceptable to approximate it with a less cpu-intensive formula? Or to reduce the number of iterations or EPSILON? This is not simple to answer this question for me at the moment.
