### ISSUE TITLE
ZamGEQ31 fails at 44100 Htz when moving the 20k's fader

### ISSUE THREAD

**Issue by sub26nico** [zamaudio/zam-plugins#68]
I have an issue using ZamGEQ31 with Jack's sample rate at 44100 htz, if I move up or down 
the fader of 20k's band. The sound of the host (Ardour 5.12, Qtractor 0.9.2, Reaper 5.96) is down 
until I reset the preset. No issues with sample rate at 48k Htz.

zamplugins  3.10 
Distro : LibraZiK2 (audio oriented distro based on Debian Stretch)

**Comment by jujudusud** [comment]
The 20kHz fader = 22,4kHz in the plugin.
You can't use it under 48kHz because of Nyquist ...
2 Solutions :
- use it at 48kHz
- change the reel band to 44.1/2 = 22.05kHz or under (ultrason domain). Rebuild the plugin...

**Comment by jujudusud** [comment]
PR #72 is ok when using the plugin on my computer.

**Comment by sub26nico** [comment]
Same here, with PR #72, I can't reproduce the bug anymore. Moving the 20k fader doesn't make fail the sound of the host anymore (tested ladspa, lv2 and vst in Ardour and Qtractor, and vst in Reaper).

**Comment by zamaudio** [comment]
Merged
