### ISSUE TITLE
ZaMaximX2 Not processing anything?

### ISSUE THREAD

**Issue by winterheartlee** [zamaudio/zam-plugins#71]
Hi all,
I've recently compiled the zam audio plugins as they are and all seem to be working fine except the ZaMaximX2, it just doesn't seem to do anything regardless or threshold and ceiling settings; there's no audible or visual gain reduction. Can't see this in the current or closed issues so just wondering if anyone has any ideas?
I'm using the 32bit windows vst build.
Thanks

**Comment by zamaudio** [comment]
No idea, I don't have windows to test.

**Comment by zamaudio** [comment]
BTW the default settings of the plugin is a transparent no-operation.  To get an audible difference you must lower the threshold for example.

**Comment by zamaudio** [comment]
Another user has reported Win64 version of VSTs processing as if bypassed.  Will need further investigation.

**Comment by winterheartlee** [comment]
Apologies for the delay, but yeah I did play around with settings and never saw/heard any gain reduction... ok cool, glad its not only me :) 
Cheers!

**Comment by zamaudio** [comment]
That other user who reported win64 was not working with VSTs said he tweaked something in the host application and it suddenly worked.  @winterheartlee I suggest you check the VST host you are using and double check the application settings.

**Comment by zamaudio** [comment]
Closing stale issue
