### ISSUE TITLE
make install errors on macOS: illegal option `install -t` 

### ISSUE THREAD

**Issue by mauritslamers** [zamaudio/zam-plugins#73]
As described in the title, I get an error when installing the zam plugins on macOS (Mojave 10.14.2), as it doesn't recognize the `-t` option provided to the install command.

**Comment by mauritslamers** [comment]
The reason I am making an issue of it, is that the path `make install` will install the plugins by default is correct, except that the install command uses an illegal option for macOS (and by extension probably also all BSDs). I was just wondering whether a small change to the make file would allow it to be used directly on macOS.

**Comment by zamaudio** [comment]
This is no longer an issue thanks to .pkg installer
