### ISSUE TITLE
SFZero code included without MIT license text

### ISSUE THREAD

**Issue by jamiebullock** [zamaudio/zam-plugins#74]
I notice your project includes a `libsfz` which incorporates modified versions of substantial portions of code from [SFZero](https://github.com/stevefolta/SFZero), e.g. from the `SFZReader` class. I have worked very closely with SFZero, and so the code is unmistakeable to me. 

I'm not sure if you did this deliberately, but it is a violation of the SFZero's MIT license  to remove that license and re-license the modified code under the GPL. 

Can I therefore politely ask that you either license `libsfz` under the MIT license including the original copyright notice as required [here](https://github.com/stevefolta/SFZero/blob/master/License), or  remove `libsfz` and replace it with a fully-refactored version that doesn't include substantial portions of code from `SFZero`, in which case you can license it however you wish.

**Comment by zamaudio** [comment]
Fixed in f2d73e5
