### ISSUE TITLE
ZaMultiComp(X2) high DSP load 

### ISSUE THREAD

**Issue by pdesaulniers** [zamaudio/zam-plugins#75]
I really like ZaMultiCompX2! However, on my machine, running one idle instance of this plugin in jalv raises the Jack DSP load to almost 40%, which I think is too high. 

It seems like most of the overhead comes from the averageabs function:
![2019-03-07-19 16 16](https://user-images.githubusercontent.com/23723605/53998411-957eb480-410d-11e9-8334-c64983a38638.png)

**Comment by zamaudio** [comment]
How did you generate that table?  I have addressed this issue and reduced load with other compressors in 82b1811

**Comment by pdesaulniers** [comment]
I used callgrind and kcachegrind. Basically:
```
DEBUG=true make
valgrind --tool=callgrind bin/ZaMultiCompX2

# run the program for a while, then close it

kcachegrind callgrind.out.XXX
```


Anyway, it's working great now, thanks!

**Comment by zamaudio** [comment]
Please use commit d211bff as the above commit I recommended before has a floating point accumulation bug.

**Comment by zamaudio** [comment]
The moving dots that show the current level per band are now much smoother too.

**Comment by jrigg** [comment]
Thanks for this. CPU load of standalone JACK version has dropped from 33% to 25% here. Nice improvement.
