### ISSUE TITLE
Cross build for ARM: Segmentation fault during ZamVerb lv2-ttl-generate

### ISSUE THREAD

**Issue by schnitzeltony** [zamaudio/zam-plugins#77]
**Preliminary background:** 
I build all music stuff cross with openembedded/yocto. Since the DPF turtle generation with lv2-ttl-generator does not work in cross builds - plugins are build for ARM - I implemented two ways to get around:

1. Manipulate build to keep plugins names for ttl-generation instead of performing lv2-ttl-generator and postpone turtle generation with qemu. Some plugins cause qemu crashes (zamp-plugins is one of those) so I created a second way:
2. Keep plugins name during compile (same as 1), install this information on target machine and run all turtle generation at first boot.

**Symptom:**
Running ttl-genaration on target machine segfaults for ZamVerb:

>root@raspberrypi3:ZamVerb.lv2# lv2-ttl-generator /usr/lib/lv2/ZamVerb.lv2/ZamVerb_dsp.so 
>Generate ttl data for '/usr/lib/lv2/ZamVerb.lv2/ZamVerb_dsp.so', basename: 'ZamVerb_dsp'
>convolution: samplerate mismatch preset:48000 host:44100
>Segmentation fault

**Debugging the symptom:**
Here is a screenshot of the point of crash:
![zita-crash](https://user-images.githubusercontent.com/2571823/66261899-eb1b5c80-e7d5-11e9-8574-4b26af7113da.png)

This is all I have currently - if you cannot reproduce and want me to set breakpoints / take further screenshots - let me know

**Comment by zamaudio** [comment]
Looks like a bug in zita-convolver for ARM ?  Maybe you need to disable vector mode, I'm not sure.

**Comment by schnitzeltony** [comment]
Meanwhile I moved builds to aarch64 and the problem is gone there. Since - as you mentioned - it seems a problem outside this project, I close this one. Thanks for looking into.
