### ISSUE TITLE
changelog updates in GitHub release messages?

### ISSUE THREAD

**Issue by mxmilkiib** [zamaudio/zam-plugins#81]
I'm currently putting together a release news aggregator - https://libreav.org/updates - and I was wondering if I can request that the changelog text could be included in the release message texts so that it comes through via the GH releases.atom feed?

**Comment by zamaudio** [comment]
@mxmilkiib I don't like adding value to parts of github that are proprietary.  Sorry

**Comment by mxmilkiib** [comment]
Is that not contradictory, given the rest of the system is not open and you still use it?

If your principal is openness, does sharing information using an open syndication format not  align with that?

**Comment by zamaudio** [comment]
I am also trying to make a few $ on the binaries, so I need to point people to my online shop.  That's the reason for just a link in the release notes.

**Comment by mxmilkiib** [comment]
I don't think that you putting changelogs in the release notes would stop people clicking on the link in the first line to your website. In fact I think if you added that detail it would actually give people a reason/context to click through.
