### ISSUE TITLE
Update to latest DPF

### ISSUE THREAD

**Issue by falkTX** [zamaudio/zam-plugins#86]
Hi Damien, hope everything is well.
I really like your plugins but sadly they have been falling behind regarding the DPF version they use.
A few of the issues reported have been fixed quite long time ago, plus there is VST3 and CLAP support now.

I would like to update them, but want to ask first if there is interest before putting in the work for it.
The custom knob handling I would leave as-is for now. But would be nice to get all the latest fixes and latest features as well.

PS: regarding AU, no news on that side yet. VST3 was done first because it is more common, then CLAP due to such work being sponsored.

**Comment by zamaudio** [comment]
Hi Filipe, going well thanks.
Yes, unfortunately my CI would no longer work too because you removed `ppa:kxstudio-debian/mingw`.
I am happy to update DPF, and I'd like to make sure I can still build for MacOS and Windows.
But is MacOS getting more difficult to support?

**Comment by falkTX** [comment]
> Yes, unfortunately my CI would no longer work too because you removed `ppa:kxstudio-debian/mingw`.

sorry I needed to make space for other toolchain packages, the mingw stuff was old and stock ubuntu stuff now works fine, assuming a ubuntu 20.04 or higher.

> I am happy to update DPF, and I'd like to make sure I can still build for MacOS and Windows.
> But is MacOS getting more difficult to support?

quite the contrary, I have real macOS hw now so I test it from time to time.
additionally github actions became a thing, which provides a native macOS builder.
using https://github.com/DISTRHO/dpf-makefile-action as the action we very easily get linux/mac/win build without any effort, just create a file alike this https://github.com/DISTRHO/Kars/blob/master/.github/workflows/build.yml and magic happens :)
only issue becomes if you dont want to have release binaries through github (to keep them commercial, for example). if that is still the case, then you would still need to do the builds yourself..

**Comment by zamaudio** [comment]
Thank you for doing the work to port my plugins over to latest dpf.  As discussed, I will update my website to point to the gratis builds.

**Comment by zamaudio** [comment]
Next release will be coming soon.
