### ISSUE TITLE
Sample rate changes

### ISSUE THREAD

**Issue by falkTX** [zamaudio/zam-plugins#90]
For VST3 and CLAP plugin formats, the runtime sample rate is not known when the plugin is first created.
Only when plugin gets activated by the host do we know this information.
DPF handles this by triggering a sample rate change callback, informing the plugin (and UI) of the change.

In order to get zam plugins working nicely in these formats, they need to implement sample rate changes.

**Comment by falkTX** [comment]
Fixed by #91

**Comment by zamaudio** [comment]
Merged 91, closing
