### ISSUE TITLE
Autosat VST3: Failed to load chunk data warning on Ardour.

### ISSUE THREAD

**Issue by lee-yunseok** [zamaudio/zam-plugins#94]
When load Autosat or open session contains Autosat, the warning shows in the **Ardour log**. This warning only appears with VST3, the **LV2 plugin has no warning**.

Hardware: Raspberry Pi 4B 8GB RAM
OS: RasPiOS ARM64
DAW: Ardour
Zam: 4.0 Releases

**Comment by falkTX** [comment]
maybe state is empty?

**Comment by lee-yunseok** [comment]
![2022-12-16-201120_1920x1080_scrot](https://user-images.githubusercontent.com/5509466/208086165-6c046a23-763b-47f8-9e35-2288111dea2d.png)

It just loaded.

**Comment by falkTX** [comment]
I see plugin has no state or parameteres whatsoever.
This might be throwing off Ardour VST3 implementation, you can safely ignore the warning because there is no state to load at all for AutoSat.
Consider reporting a bug/ticket against Ardour though.

**Comment by lee-yunseok** [comment]
Okay I will.
