### ISSUE TITLE
Feature request - ZaMultiCompX2 - Mono button on LF band

### ISSUE THREAD

**Issue by jrigg** [zamaudio/zam-plugins#95]
A mono button on the LF band of ZaMultiCompX2 would be very useful for mastering for vinyl.

**Comment by zamaudio** [comment]
@jrigg I'm a bit reluctant to change the number of controls on plugins, as this breaks LV2.  The MAX/Average switch doesn't seem to have much effect.  Maybe I could make the average side of the switch toggle LF mono?

**Comment by jrigg** [comment]
Fair point about LV2 breakage. I overlooked that as I mostly use the JACK version. Losing the Average setting and repurposing the switch to toggle  LF mono would work for me, but I don't know how other users would feel.

**Comment by zamaudio** [comment]
@jrigg I suggest you try jalv.gtk with the LV2 versions because you can save/load presets which the JACK version cannot do.  I have created a branch with your suggested changes.  https://github.com/zamaudio/zam-plugins/compare/master...zamulticompx2-mono-lf can you try it out and let me know if you think its worth merging?

**Comment by jrigg** [comment]
Looks good on quick initial test but ran out of time for more extensive testing. I'll do more testing tomorrow (UK time) and report back.

**Comment by jrigg** [comment]
Still good after further testing. On my test material (heavy rock in low B tuning) the mono bass mode sounds more powerful and focussed than in MAX mode.  I'd probably use this whatever the release format, not just vinyl.

One possible caveat would be that hard-panned MF and HF sounds might shift in the stereo image due to the averaging, but it didn't cause a noticeable problem here.

BTW the reason I mostly use the JACK version is lower CPU load. It's about 8% on my Ryzen sytem, dropping to 4% if I hide the window (in cwm window manager) after settimg it up.  The LV2 in jalv.gtk3 is about 10% load, dropping to 9% when hiding the window. IIRC jalv.gtk (GTK2) was better, but jalv recently dropped GTK2 support.

**Comment by zamaudio** [comment]
@jrigg merged in 2ef55cf

**Comment by jrigg** [comment]
Thanks for your work on this. Best wishes for 2023.

**Comment by zamaudio** [comment]
@jrigg in case you didn't notice this new feature, seems to work with JACK version:

`$ DPF_SCALE_FACTOR=1.5 ZaMultiCompX2`

**Comment by jrigg** [comment]
Thanks for the tip. That's a useful feature.
