### ISSUE TITLE
Error compile (make)  "ZamHeadX2" samplerate was not found in the pkg-config

### ISSUE THREAD

**Issue by davidben009** [zamaudio/zam-plugins#96]
im receiving error on make command !!! how to fix this?

make -C plugins/ZamHeadX2
make[1]: Entering directory '/home/david/Downloads/zam-plugins/plugins/ZamHeadX2'
Package samplerate was not found in the pkg-config search path.
Perhaps you should add the directory containing `samplerate.pc'
to the PKG_CONFIG_PATH environment variable
Package 'samplerate', required by 'virtual:world', not found
Package 'fftw3f', required by 'virtual:world', not found
Compiling convolution.cpp
convolution.cpp:45:10: fatal error: samplerate.h: No such file or directory
   45 | #include <samplerate.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [../../dpf/Makefile.plugins.mk:384: ../../build/ZamHeadX2/convolution.cpp.o] Error 1
make[1]: Leaving directory '/home/david/Downloads/zam-plugins/plugins/ZamHeadX2'
make: *** [Makefile:29: ZamHeadX2] Error 2

**Comment by zamaudio** [comment]
Perhaps read the error message?  It says you are missing libsamplerate and libfftw3f libraries.

**Comment by zamaudio** [comment]
Closing as user error.
