### ISSUE TITLE
Unusable on Windows with Audacity (VST)

### ISSUE THREAD

**Issue by polyzium** [zamaudio/zam-plugins#97]
![Audacity_0UvYxbrIf4](https://github.com/zamaudio/zam-plugins/assets/22579935/24c2bd25-06e0-4cff-af04-fc0fa1b5946d)

**Comment by zamaudio** [comment]
Duplicate issue of #99, see comment there.

**Comment by polyzium** [comment]
You can't be serious, I opened this issue way before this guy did.

Oh well, let's see if it's fixed in newer DPF.
