### ISSUE TITLE
ZamHeadX2 array indices swapped

### ISSUE THREAD

**Issue by Hamster128** [zamaudio/zam-plugins#98]
Hi,

I just build your ZamHeadX2 plugin, and on the way to understand the parameters, i think i came across a bug. It seems that the dimensions of the fir_left/right arrays are swapped:

void ZamHeadX2Plugin::reload()
elev 0 - 24
azim 0 - 49

clv_configure("convolution.ir.preset", elev, azim);

.
.
.

LV2convolv::clv_configure (const char *key, const char *elev, const char* azim)

ir_presetx = atoi(elev);	// 0 - 24
ir_presety = atoi(azim);        // 0 - 49

.
.
.

LV2convolv::clv_initialize (

fir_coeffs_lr[2 * i] = fir_left[ir_presetx][ir_presety][i];
fir_coeffs_lr[2 * i + 1] = fir_right[ir_presetx][ir_presety][i];

here we have fir_left[ 0 - 24 ][ 0 - 49 ] [i]
but it was defined with swapped ranges:
static const float fir_left[50][25][200] = {

**Comment by zamaudio** [comment]
Thanks for bug report, will address soon.

**Comment by zamaudio** [comment]
Fixed in 4.2
