### ISSUE TITLE
vst2 Version doesn't work right in Audacity

### ISSUE THREAD

**Issue by stefan-franz** [zamaudio/zam-plugins#99]
The adjustment of the value wheel works not right e.g. ZaMaximX2 - if you adjust the level wheels, you see what i mean. 
Vst3 works fine. 
Addional: Vst3 Vers. 4.1 - the LED doesn't work e.g. in ZaMaximX2
And the the older vst2 3.14 seems work perfect.

**Comment by zamaudio** [comment]
I don't know why people try to use VSTs in Audacity.  My plugins are real-time effects and are supposed to be applied in a non-linear editor (NLE) such as Ardour DAW.  It does not make sense to monitor the LEDs in a one-shot processing mode.  I am not surprised it is not working.  I don't see how I can fix this, it's a problem with Audacity's mode of operation; it is not a NLE.

**Comment by zamaudio** [comment]
Could be fixed in DISTRHO/DPF/issues/398 I will update DPF.

**Comment by zamaudio** [comment]
Should be fixed in zam-plugins@4.2

**Comment by stefan-franz** [comment]
Wow - Great support. 
Audacity has now a realtime feature so for a quick sound optimizing on my DJ Laptop with Linux Mint your Plugins are fine. 
Normal i use it with Ardour.
Btw: The VST3 versions have also the problem with not working LED - but the vst2 are working fine on my first test.

**Comment by zamaudio** [comment]
Closing as fixed
